### ISSUE TITLE
J+S Konformität überprüfen

### ISSUE THREAD

**Issue by andystoeggle** [PfadiAngenstein/ecamp2#1]
J+S Konformität soll geprüft werden können. Möglich wäre ein zusätzlicher Button neben _Darstellung_ im Picasso, welcher die Tage entsprechend einfärbt.

**Comment by EloquentZebra** [comment]
Der Vollständigkeit halber, folgende Dinge machen einen Tag J+S-konform:

- min. 4h J+S- Blöcke
  - min. 2h LS
  - max. 2 LA
- J+S-Blöcke auf 2 von 3 Tagesdritteln verteilt
  Tagesdrittel Vormittag, Nachmittag, Abend; die Drittel werden durch die Mahlzeiten geteilt
- LS min. 30min
- LA min. 1h
- Reisetagregelung berücksichtigen?
  (An- und Abreisetag zählen jeweils halb, resp. müssen nur zusammen einen J+S-Tag ergeben)
