### ISSUE TITLE
Dokumentenablage

### ISSUE THREAD

**Issue by tierriminator** [PfadiAngenstein/ecamp2#18]
Um ein Lager vollständig auf ecamp zu planen sollte es eine Dokumentenablage geben, auf welche Dokumente wie Broschüre, Lagerdruck, Lagerplatzvertrag, etc. gespeichert werden können.

**Comment by andystoeggle** [comment]
Wurde realisiert auf der Seite 'Infos zum Lager' (siehe Commit 3accfe377b3b1585b5870a4d1559cc9ebe494db0)
