### ISSUE TITLE
MiData-Schnittstelle

### ISSUE THREAD

**Issue by EloquentZebra** [PfadiAngenstein/ecamp2#8]
Die MiData verfügt über eine rudimentäre JSON-Schnittstelle.

Rudimentäre Dokumentation unter folgendem Link: [Dropbox](https://www.dropbox.com/sh/n1lnubh87oq6p5p/AAApZuLm4vh7fXlTezsvE9wBa/JSON%20Schnittstelle_20151002.pdf?dl=0)

Diese kann zwar nicht als Identity Provider genützt werden, aber evtl. zur Erzeugung der User sowie allfällig für den Import von Lagerdaten -> müsste dann nur an einem Ort gepflegt werden.

Die Schnittstelle ist nicht so gut kommentiert, da müsste getest werden was alles möglich ist.

**Comment by andystoeggle** [comment]
Angedachte Funktionsweise:
User loggt sich mit seinen MiData Credentials ein, welche an die MiData API übermittelt werden. Ist die Authentisierubg erfolgreich (Auth-Token in Response) so werden mit diesem die Personeninfos abgerufen. Ist die Person Mitglied der Pfadi Angenstein (Abgleich mit entsprechender Gruppenzugehörigkeit) so wird diese in die lokale Usertabelle eingetragen (inkl. md5-Hash des aktuellen Kennworts). Damit können sich die User bei einem Ausfall der MiData immernoch mit dem letzten PW einloggen (Login-Type-Parameter in config).

**Comment by andystoeggle** [comment]
Wurde wie oben beschrieben realisiert und getestet.
